sudo: false
language: node_js
node_js:
- '12'
install:
- npm install -g pkg
script:
- bash build.sh
- bash tp-userprog.sh
- ls -alh ./release
env:
- NODERED_VERSION=1.0.6
deploy:
  provider: releases
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    repo: stsparrow/pkg-node-red
    tags: true
