sudo: false
language: node_js
node_js:
- '8'
install:
- npm install -g pkg
script:
- bash build.sh
- bash tp-userprog.sh
env:
- NODERED_VERSION=0.19.4
deploy:
  provider: releases
  api_key:
    secure: OXj7RI5SXSWpAtS1FHiN0/BcYl6376t5+Jn51Te4XhU2O0DYtSITpm23zfhFGwcyi173Pjg6S1v9GEublMKyAFGwdtn848d0z9xwH4Qwzsp3FpGiel1n4K/tOG+cx7K1Ub/cFGE8xbziE9YiI0wkFI+h7K1oOe0dIxvvPCLIST1/4a/H/mEhL9IXynTUgVdwR8m/AP40FMRN74ZpQ182nA/ZwgVP1z/n75dH0xds9iTo+GKnXkveSFgl71BWPEGhCBrAJzeFarVVRUKjK27RzC8zpDSVzBZAP9NAFeLuCkLnKt1EkXTzNM6/EDUWRrXdY38QXdBxvvWMgjeOJ4YYiYnaNvXegczqsQdmUURe8McfcF16KEZaC0FpCDleDeokideEoxrSrh5nmqcYb6NYlcwnCDicX+RGQhYT6HPhpN8eO8RI5NbyA28DfzWyv89MbtnLOcUm+NgRGbt971o9yjjYfM2vezUDYz9Fu9/V4yOfDP8LPftFVHXccl3eBKsYPhU2H9L0OQ7Kl8mBd4oK9HXqLCAAvgMp1falUFJO5yvYldcnJhuFMHYYfx9ysIeQI/I6RNvcmQO5sFtEyDs4h/i2chxfpxRAe41+OSrS/Je2RnvJIsC0MCQ23hsRvdDe3i3qMpL/crddUn2CsGxmGv/mn0e/W0qFyPbVyw6MOuA=
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    repo: imZack/pkg-node-red
    tags: true
